### Guilherme Holanda Sanches - 10734370
# Projeto 1 - Neural Networks
---
### Questão 1:
* A) Observando os dados da base de treino fornecida, é possível notar um grande desbalanceamento entre as classes no que se refere à quantidade de exemplos fornecidos. Portanto a métrica AUC (Area Under the Curve) é mais adequada para avaliar o desempenho do sistema em comparação com a acurácia. Isso ocorre porque a AUC leva em consideração tanto a taxa de verdadeiros positivos quanto a taxa de falsos positivos, fornecendo uma medida mais abrangente da capacidade do modelo em classificar corretamente as amostras de ambas as classes, mesmo quando a distribuição dos dados é desigual.

* B) - (Lendo os dados e gerando "respostas" todas negativas e positivas no mesmo tamanho das respostas do test.csv)


In [1]:
import pandas as pd

train_df = pd.read_csv('test.csv')
train_df

V1         V2        V3        V4        V5        V6  \
0       -0.439952   0.683758  1.225814  0.639113  0.716765  0.089295   
1       -4.868108   1.264420 -5.167885  3.193648 -3.045621 -2.096166   
2        1.013114  -0.334412  1.305208  0.837406 -1.126833 -0.064321   
3        0.969231  -0.233554  0.238473  0.145793 -0.545741 -0.970680   
4       -0.856523   1.080875  1.866956  1.729941 -0.161741  0.028789   
...           ...        ...       ...       ...       ...       ...   
142398 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
142399  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
142400   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
142401  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
142402  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V20       V21  \
0       0.657718  0.034213 -0.472679  0.352698  ...  0.211867  0.127443   
1      -6.445610  2.422536 -3.214055 -8.745973  ...  0.667310  1.269205   
2      -0.594753  0.147737  0.536360 -0.120472  ...  0.069161  0.017079   
3       0.347393 -0.209522 -0.342571 -0.100331  ...  0.240978 -0.362820   
4       0.401787  0.043774 -0.213916  0.155907  ... -0.068915  0.007365   
...          ...       ...       ...       ...  ...       ...       ...   
142398 -4.918215  7.305334  1.914428  4.356170  ...  1.475829  0.213454   
142399  0.024330  0.294869  0.584800 -0.975926  ...  0.059616  0.214205   
142400 -0.296827  0.708417  0.432454 -0.484782  ...  0.001396  0.232045   
142401 -0.686180  0.679145  0.392087 -0.399126  ...  0.127434  0.265245   
142402  1.577006 -0.414650  0.486180 -0.915427  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.588590 -0.145728 -0.322900 -0.299744 -0.310295  0.248317 -0.011493   
1       0.057657  0.629307 -0.168432  0.443744  0.276539  1.441274 -0.127944   
2       0.112210 -0.016084  0.595033  0.201073  0.278215  0.007457  0.030762   
3      -1.417272  0.162136  0.541628 -0.079465  0.268702 -0.101237  0.028234   
4       0.077392 -0.221906  0.394141  0.237225 -0.080102 -0.291408  0.092140   
...          ...       ...       ...       ...       ...       ...       ...   
142398  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
142399  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
142400  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
142401  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
142402  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Class  
0           0  
1           1  
2           0  
3           0  
4           0  
...       ...  
142398      0  
142399      0  
142400      0  
142401      0  
142402      0  

[142403 rows x 29 columns]

In [2]:
test_df = pd.read_csv('test.csv')
test_df

V1         V2        V3        V4        V5        V6  \
0       -0.439952   0.683758  1.225814  0.639113  0.716765  0.089295   
1       -4.868108   1.264420 -5.167885  3.193648 -3.045621 -2.096166   
2        1.013114  -0.334412  1.305208  0.837406 -1.126833 -0.064321   
3        0.969231  -0.233554  0.238473  0.145793 -0.545741 -0.970680   
4       -0.856523   1.080875  1.866956  1.729941 -0.161741  0.028789   
...           ...        ...       ...       ...       ...       ...   
142398 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
142399  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
142400   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
142401  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
142402  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V20       V21  \
0       0.657718  0.034213 -0.472679  0.352698  ...  0.211867  0.127443   
1      -6.445610  2.422536 -3.214055 -8.745973  ...  0.667310  1.269205   
2      -0.594753  0.147737  0.536360 -0.120472  ...  0.069161  0.017079   
3       0.347393 -0.209522 -0.342571 -0.100331  ...  0.240978 -0.362820   
4       0.401787  0.043774 -0.213916  0.155907  ... -0.068915  0.007365   
...          ...       ...       ...       ...  ...       ...       ...   
142398 -4.918215  7.305334  1.914428  4.356170  ...  1.475829  0.213454   
142399  0.024330  0.294869  0.584800 -0.975926  ...  0.059616  0.214205   
142400 -0.296827  0.708417  0.432454 -0.484782  ...  0.001396  0.232045   
142401 -0.686180  0.679145  0.392087 -0.399126  ...  0.127434  0.265245   
142402  1.577006 -0.414650  0.486180 -0.915427  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.588590 -0.145728 -0.322900 -0.299744 -0.310295  0.248317 -0.011493   
1       0.057657  0.629307 -0.168432  0.443744  0.276539  1.441274 -0.127944   
2       0.112210 -0.016084  0.595033  0.201073  0.278215  0.007457  0.030762   
3      -1.417272  0.162136  0.541628 -0.079465  0.268702 -0.101237  0.028234   
4       0.077392 -0.221906  0.394141  0.237225 -0.080102 -0.291408  0.092140   
...          ...       ...       ...       ...       ...       ...       ...   
142398  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
142399  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
142400  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
142401  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
142402  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Class  
0           0  
1           1  
2           0  
3           0  
4           0  
...       ...  
142398      0  
142399      0  
142400      0  
142401      0  
142402      0  

[142403 rows x 29 columns]

In [3]:
import numpy as np
from sklearn.metrics import roc_auc_score, accuracy_score
test_size = test_df['Class'].count()
all_true = np.zeros(test_size)
all_false = np.ones(test_size)

auc_false = roc_auc_score(test_df['Class'], all_false)
auc_true = roc_auc_score(test_df['Class'], all_true)

acc_false = accuracy_score(test_df['Class'], all_false)
acc_true = accuracy_score(test_df['Class'], all_true)

In [4]:
print(auc_false, auc_true, acc_false, acc_true)

0.5 0.5 0.0015659782448403474 0.9984340217551596


### Questão 2

In [5]:
X_train = train_df.drop('Class', axis='columns')
y_train = train_df['Class']
X_test = test_df.drop('Class', axis='columns')
y_test = test_df['Class']

In [6]:
from sklearn.neural_network import MLPClassifier
alphas = [0.0, 0.01, 0.1, 1, 10]

for alpha in alphas:
    # Criando o classificador MLP com o valor atual de alpha
    mlp = MLPClassifier(hidden_layer_sizes=(20, 20, 20, 20, 20),
                        activation='relu',
                        alpha=alpha,
                        random_state=42)

    mlp.fit(X_train, y_train)
    predictions = mlp.predict(X_test)

    # Avaliando o desempenho
    accuracy = roc_auc_score(y_test, predictions)
    print(f"Modelo com alpha={alpha}: AUC = {accuracy}")


Modelo com alpha=0.0: AUC = 0.9417040358744395
Modelo com alpha=0.01: AUC = 0.9102857679932025
Modelo com alpha=0.1: AUC = 0.8743972618552748
Modelo com alpha=1: AUC = 0.5852017937219731
Modelo com alpha=10: AUC = 0.5


Portanto é possivel observar que a taxa de regularização influencia na medida do resultado, quanto menor o alpha, mais acertos.

---
### Questão 3
(Primeira análise)

In [7]:
from sklearn.model_selection import cross_val_score, StratifiedKFold

kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

layers = [(), (10,), (5, 5)]
scores_NN = []

for n_layer in layers:
    mlp = MLPClassifier(hidden_layer_sizes=n_layer,
                        random_state=42)
    
    mlp.fit(X_train, y_train)
    # Realizando a validação cruzada
    scores_NN.append(cross_val_score(mlp, X_train, y_train, cv=kfold))
    
scores_NN
    

[array([0.99932586, 0.9996208 , 0.99955759]),
 array([0.99932586, 0.9994944 , 0.99957865]),
 array([0.99934693, 0.99964186, 0.99962079])]

In [8]:
from sklearn.neighbors import KNeighborsClassifier

ks = [3, 5, 7]
scores_kfold = []

for n_k in ks:
    knn = KNeighborsClassifier(n_k)
    knn.fit(X_test, y_test)
    
    scores_kfold.append(cross_val_score(knn, X_train, y_train, cv=kfold))
    

scores_kfold

[array([0.99932586, 0.99945226, 0.99962079]),
 array([0.99930479, 0.99947333, 0.99964186]),
 array([0.99930479, 0.99947333, 0.99966292])]

In [9]:
np.sum(np.subtract(scores_NN, scores_kfold))

0.00025279833702418486


#### Análise com GridSearchCV

In [10]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

mlp = MLPClassifier(random_state=42)

mlp_parameters = [
    {'hidden_layer_sizes': [()]},
    {'hidden_layer_sizes': [(10,)]},
    {'hidden_layer_sizes': [(5, 5)]}
]
# Criando o objeto GridSearchCV para cada classificador
mlp_grid_search = GridSearchCV(mlp, mlp_parameters, cv=3)


# %%time
# Realizando a pesquisa em grade para cada classificador
mlp_grid_search.fit(X_train, y_train)

# Imprimindo os melhores hiperparâmetros encontrados para cada classificador
print("Melhores hiperparâmetros para MLPClassifier:")
print(mlp_grid_search.best_params_)

Melhores hiperparâmetros para MLPClassifier:
{'hidden_layer_sizes': (10,)}


In [11]:
# Avaliando o desempenho dos melhores modelos para cada classificador
mlp_accuracy = mlp_grid_search.score(X_test, y_test)

print(f"Acurácia do melhor modelo MLPClassifier: {mlp_accuracy}")

Acurácia do melhor modelo MLPClassifier: 0.9996488838016053


In [12]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn_parameters = [
    {'n_neighbors': [3]},
    {'n_neighbors': [5]},
    {'n_neighbors': [7]}
]

knn_grid_search = GridSearchCV(knn, knn_parameters, cv=3)
# %%time
knn_grid_search.fit(X_train, y_train)


print("Melhores hiperparâmetros para KNeighborsClassifier:")
print(knn_grid_search.best_params_)


Melhores hiperparâmetros para KNeighborsClassifier:
{'n_neighbors': 7}


In [13]:
knn_accuracy = knn_grid_search.score(X_test, y_test)

print(f"Acurácia do melhor modelo KNeighborsClassifier: {knn_accuracy}")

Acurácia do melhor modelo KNeighborsClassifier: 0.999536526618119


In [14]:
mlp_accuracy - knn_accuracy

0.0001123571834863446

* A) A técnica de utilizar a rede neural com uma camada intermediária com 10 neuronios se mostrou mais vantajosa comparada ao KNN pois obteve um score 0.00011 maior.
* B) O KNN demorou muito mais para gerar as previsões em relação ao MLPClassifier por que o algoritmo precisa calcular a distância dos dados de treinamento para todas as outros dados do conjunto de treinamento. 
---
### Questão 4

In [15]:
best_model = mlp = MLPClassifier(random_state=42,  hidden_layer_sizes=(10,))
best_model.fit(X_train, y_train)

transactions = best_model.predict_proba(X_test)

transactions

array([[9.99878056e-01, 1.21944110e-04],
       [1.64489863e-05, 9.99983551e-01],
       [9.99155554e-01, 8.44445511e-04],
       ...,
       [9.99986250e-01, 1.37503010e-05],
       [9.99999844e-01, 1.56269857e-07],
       [9.99967297e-01, 3.27030049e-05]])

In [16]:
one_percent = int(len(transactions) * 0.01)

probs_fraud = transactions[:, 1]
sorted_indices = np.argsort(probs_fraud)[::-1]
sorted_indices = sorted_indices[: one_percent]

In [17]:
frauds = transactions[sorted_indices]

not_frauds = [transaction for transaction in frauds if transaction[0] >= transaction[1]]
n_true_blocks = len(frauds) - len(not_frauds)

gains = 100 * n_true_blocks
losses = 2 * len(not_frauds)

print(f'''Se bloquearmos 1% das transações com maiores probabilidades de serem fraudes, teremos {len(frauds)} transações bloqueadas,
        sendo que {n_true_blocks} tem grande probabilidade de serem fraudes e {len(not_frauds)} não.
        baseando-se nisso, é provavel dizer que o  modelo evitaria R${gains} de perdas, e os bloqueios errôneos trariam R${losses} de prejuízo''')

Se bloquearmos 1% das transações com maiores probabilidades de serem fraudes, teremos 1424 transações bloqueadas,
        sendo que 181 tem grande probabilidade de serem fraudes e 1243 não.
        baseando-se nisso, é provavel dizer que o  modelo evitaria R$18100 de perdas, e os bloqueios errôneos trariam R$2486 de prejuízo


---
### Questão 5
* O SGDClassifier, armazena os coeficientes atribuídos a cada variável por meio do atributo coef_. Valores próximos de zero indicam que a variável tem menos impacto no modelo. Para isso vamos definir um limiar abitrário de 0.5 em difereça absoluta do 0.


In [18]:
from sklearn.linear_model import SGDClassifier

# O hiperparametro loss='log' define a função de ativação como sigmoid
sgd_classifier = SGDClassifier(loss='log', random_state=42)

sgd_classifier.fit(X_train, y_train)
sgd_classifier.coef_

c:\Users\holon\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


array([[ -1.90396652,   3.20133897, -10.07524042,  10.52191773,
          3.36484313,  -2.59997983,  -2.87231874,  -3.98241251,
         -2.58948718,  -5.88675992,   4.38061579,  -7.4802448 ,
         -0.59637301, -12.6140959 ,  -2.27653193,  -3.29237196,
         -2.75010288,   0.74038048,  -0.25889901,   0.68420487,
          2.23508381,   0.5833491 ,  -0.25864259,   0.10620122,
         -0.65497842,  -0.3124277 ,   0.34504393,   0.35544964]])

In [19]:
below_threshold = np.argwhere(np.abs(sgd_classifier.coef_[0]) < 0.5).reshape((1, -1))

below_threshold = [f'V{i+1}' for i in below_threshold[0]]

print(f'''As variáveis não importantes para o problema são: {below_threshold}''')


As variáveis não importantes para o problema são: ['V19', 'V23', 'V24', 'V26', 'V27', 'V28']
